import type { Metadata } from 'next'
import { Epilogue, Sansation, Open_Sans } from 'next/font/google'

const epilogue = Epilogue({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})
const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-open-sans',
})

const sansation = Sansation({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-sansation',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${epilogue.className} ${sansation.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
