import type { Metadata } from 'next'
import { Epilogue } from 'next/font/google'
import localFont from 'next/font/local'

const epilogue = Epilogue({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})
const openSans = localFont({
  src: [{ path: './fonts/OpenSans-Bold.ttf', weight: '700', style: 'bold' }],
  variable: '--font-open-sans',
})

const sansation = localFont({
  src: [
    {
      path: './fonts/Sansation-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Sansation-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './fonts/Sansation-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Sansation-BoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-sansation',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${epilogue.className} ${sansation.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
